version: '3.8'

services:
  eva:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /etc/nginx/sites-available:/etc/nginx/sites-available
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled
